version: "3.7"
services:
  api:
    container_name: grafana-to-ntfy
    image: grafana-to-ntfy
    restart: always
    build: .
    env_file:
      - .env
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
